config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'static_pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :services
  resources :reviews, only: [:create,:destroy,]
  resources :messages, only: [:index, :new, :create]

  get "/:page" => "static_pages#show"
 end
#root      'home#index'

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
# app/models/home.rb
class Message < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "CB Carpet Cleaning Inquiry",
      :to => "angela.inniss26@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/service.rb
class Service < ApplicationRecord
  has_many_attached :images
   scope :with_eager_loaded_images, -> { eager_load(images_attachments: :blob) }
  mount_uploader :photo, PhotoUploader
  validates :category, presence: true

  include PgSearch
  pg_search_scope :search_by_category, against: :category,
     using: {
     tsearch: { prefix: true } # <-- now `superman batm` will return something!
  }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :conversations, :foreign_key => :sender_id
  has_many_attached :images
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
     @contact = Message.new(params[:message])
  end

  def create
    @contact = Message.new(params[:message])
    @contact.request = request

    respond_to do |format|
      if @contact.deliver!
        # re-initialize Message object for cleared form
        @contact = Message.new
        format.html { render 'index'}
        format.js   { flash.now[:success] = @message = "Thank you for your message. I'll get back to you soon!" }
      else
        format.html { render 'index' }
        format.js   { flash.now[:error] = @message = "Message did not send." }
      end
    end
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
before_action :find_service, only: [:show]

  def index
    if params[:category].present?
      @services = Service.where(category: params[:category])
    else
      @services = Service.all
    end
  end

  def show
  end

  def new
    @service = Service.new
  end

  def create
   # creates service instance
    @service = Service.create(service_params)
    # if, when the user clicks submit the service is saved
    # then go back to the show page of the newly created service
    # which would be service_path(@service)
    if @service.save!
      redirect_to service_path(@service) # passing an instance of cocktail
    else
    # if service isnt created (bcz of an error or something)
    # stay on the page and show errors to user
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def service_params
    params.require(:service).permit(:name, :description, :category, :picture_url, :video, :photo, :photo_cache, images: [])
  end

  def find_service
    @service = Service.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  def show
   render params[:page]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>CB Carpet Cleaning Services</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css"/>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">


  </head>

  <body>
    <%= render 'shared/navbar'%>
    <%= render 'shared/flashes'%>
    <%= yield %>
     <%= render 'shared/footer'%>
     <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <%= javascript_pack_tag 'application' %>   <!-- from app/javascript/packs/application.js -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  </body>
</html>

app/views/messages/_contact_form.html.erb
<div class="" id="flash-message">
    <%= render 'flash' %>
</div>
<%= form_for @contact, url: messages_path, remote: true do |f| %>
    <div class="form-group">
        <%= f.label :name %></br>
        <%= f.text_field  :name, required: true, class: "form-group form-control" %></br>

        <%= f.label :email %></br>
        <%= f.text_field :email, required: true, class: "contact-form-text-area form-control" %></br>

      <%= f.label :message %></br>
      <%= f.text_area :message, rows: 8, cols: 40, required: true, class: "contact-form-text-area form-control",
                        placeholder: "Send me a message"%></br>

      <div class= "hidden">
        <%= f.label :nickname %>
        <%= f.text_field :nickname, :hint => 'Leave this field blank!' %>
      </div>

      <%= f.submit 'Send Message', class: 'button-green'%>
    </div>
  <% end %>



<!--  <div class="form-group">
     <label for="formGroupExampleInput">Name:</label>
     <input type="text"  name="name" class="form-control" id="formGroupExampleInput" placeholder="John Doe">
   </div> -->

app/views/messages/_create.js.erb
// Test for ajax success
console.log("This is the create.js.erb file");
// Render flash message
$('#contact').html("<%= j render 'contact_form' %>");
$('#flash-message').html("<%= j render 'flash' %>").delay(3000).fadeOut(4000);


  // 3. Empty out the input box
 var inputBox = document.getElementById('contact-form-text-area');
  inputBox.value = "";

app/views/messages/_flash.html.erb
<% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
<% end %>

app/views/messages/create.js.erb
// Test for ajax success
console.log("This is the create.js.erb file");
// Render flash message
$('#contact').html("<%= j render 'contact_form' %>");
$('#flash-message').html("<%= j render 'flash' %>").delay(3000).fadeOut(4000);


  // 3. Empty out the input box
 var inputBox = document.getElementById('contact-form-text-area');
  inputBox.value = "";

app/views/messages/index.html.erb
<!-- app/views/home/index.html.erb -->
<div class="bg-contact">
  <div class="container">
    <div id="social-icons-dt" data-aos="fade-down" data-aos-easing="linear" data-aos-duration="1500">
      <a href="mailto:cbcarpetcleaningservices.uk<"><i class="fas fa-at icon"> </i> </a>
      <a href="www.google.com"><i class="fab fa-facebook-f icon"></i></a>
      <a href="www.google.com"><i class="fas fa-phone"></i></a>
    </div>
     <div id="#social-icons-mobile" class="social-icons-mobile" data-aos="fade-down" data-aos-easing="linear" data-aos-duration="1500">
      <a href="mailto:cbcarpetcleaningservices.uk<"><i class="fas fa-at icon"> </i> </a>
      <a href="www.google.com"><i class="fab fa-facebook-f icon"></i></a>
      <a href="www.google.com"><i class="fas fa-phone"></i></a>
    </div>
    <h1 class="contact-us-title" class="contact-us-title-mobile">Contact Us</h1>
    <h1 class="contact-us-title-mobile">Contact Us</h1>
        <div class="row">
          <div class="col-sm">
            <h6>Drop us a note</h6>
              <i class="fas fa-grip-lines green"></i>
              <i class="fas fa-grip-lines green"></i>
              <i class="fas fa-grip-lines green"></i>
            <p>If you need urgent help please call us using the number supplied on this page. Otherwise please fill in the form below where a member of the team will respond within 24 hours. Alternatively you can contact us via FB, Phone or Email</p>

          </div>
          <div class="col-sm">
          <div id="contact" class="form-desktop" data-aos="zoom-in">
            <%= render 'contact_form' %>
          </div>
        </div>
      </div>
  </div>
 <!--  <div>
   <%= link_to 'Back to completed jobs', services_path %>
 </div> -->
  <div class="divider">
    <p> Got an emergency? Call 07931358885 now.</p>
  </div>
</div>

app/views/services/_form.html.erb
<%= simple_form_for(service) do |f| %>
  <!-- [...] -->
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-inputs">
    <%= f.input :name %>
  </div>
  <div class="form-inputs">
    <%= f.input :description %>
  </div>
    <!-- <div class="form-inputs">
    <%= f.input :picture_url %>
      </div> -->
  <div class="form-inputs">
   <!--  <%= f.input :category %> -->
     <%= f.input :category, collection: ["carpet cleaning", "rug cleaning", "curtains and blinds", "karndean"] %>
   </div>
<!--   <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
 -->
   <div class="form-inputs">
    <!--  <%= f.input :images %> -->
     <%= f.file_field :images, multiple: true %>

    </div>
    <br>
   <div class="form-actions">
     <%= f.button :submit, label: "Submit Form", class: "btn btn-primary"  %>
  </div>
<% end %>

app/views/services/index.html.erb
<!-- desktop-->
<div class="desktop-jobs">
  <h1 class="completed-desktop">Completed Jobs.</h1>
  <div class="row justify-content-around p-3">
    <% @services.each do |service| %>
      <div class="card card-main" data-aos="fade-up">
        <% if service.images.attached? %>
          <% service.images.each_with_index do |image, index| %>
            <% if index == 0 %>
              <% if image.persisted? %>
                <%= image_tag(image.variant(resize: '300x300')) %>
                <p class="text-position"><%= link_to service.name, service_path(service) %></p>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
       </div>
    <% end %>
  </div>
</div>

<!-- mobile takes service then loops through and for each service it adds an image to it-->
<div class="mobile-jobs"> <h1 class="completed-mobile">Completed Jobs.</h1>
  <div class="row justify-content-around p-3">
    <% @services.each do |service| %>
      <div class="card card-main-mobile" data-aos="fade-up">
        <% if service.images.attached? %>
          <% service.images.each_with_index do |image, index| %>
            <% if index == 0 %>
              <% if image.persisted? %>
                <%= image_tag(image.variant(resize: '300x300')) %>
                  <p class="text-position-mobile"><%= link_to service.name, service_path(service) %></p>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/services/new.html.erb
<h1>Hi Clinton upload your new job here:</h1>
<%= render 'form', service: @service %>

app/views/services/show.html.erb
<div class="background-show-2">
<div class="container">
<div class="row padding">
<div class="col-sm col-lg-4">
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
<% if @service.images.attached? %>
  <div class="carousel-inner">
    <% @service.images.each_with_index do |image, index| %>
      <% if index == 0 %>
        <div class="carousel-item active d-block w-100">
          <%= image_tag(image,:size => "400x400")%>
        </div>
      <% else %>
        <div class="carousel-item">
          <%= image_tag(image, :size => "400x400") %>
        </div>
      <% end %>
    <%end %>
  </div>
<%end %>


<% if @service.images.attached? %>
  <ol class="carousel-indicators">
    <% @service.images.each_with_index do |image, index| %>
      <% if index == 0 %>
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active">
          <%= image_tag(image,:size => "50x50")%>
        </li>
        <% elsif index == 1  %>
        <li data-target="#carouselExampleIndicators" data-slide-to="1">
          <%= image_tag(image,:size => "50x50")%>
        </li>
        <% elsif index == 2 %>
        <li data-target="#carouselExampleIndicators" data-slide-to="2">
          <%= image_tag(image,:size => "50x50")%>
        </li>
        <% else%>
        <li data-target="#carouselExampleIndicators" data-slide-to="2">
          <%= image_tag(image,:size => "50x50")%>
        </li>
      <%end %>
    <%end %>
  </ol>
<%end %>
<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</div>



    <div class="col-sm col-lg-8">
    <h2><%= @service.name %></h2>
    <p class="breadcrumb"> All jobs | Contact | About </p>
      <p><%=@service.description%></p>
    </div>
  </div>

<div>
  <iframe width="560" height="315" src="https://www.youtube.com/embed/MNNYGt_fCdk" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>
</div>
</div>

app/views/shared/_navbar.html.erb
<!-- Black main navigationon on desktop  -->
<div class="desktop-nav">
  <div>
     <li class="nav-item active">
       <%= link_to 'Home', root_path, class: "nav-link" %>
    </li>
  </div>
     <li class="nav-item active">
        <%= link_to "About", "/about", class: "nav-link" %>
     </li>

     <li class="nav-item">
        <%= link_to "Contact", "/messages", class: "nav-link" %>
     </li>
     <li class="nav-item" id="completed-job-nav">
        <%= link_to "All completed jobs", services_path, class: "nav-link" %>
     </li>
     <!--   <li class="nav-item">
       <%= link_to "Login", new_user_session_path, class: "nav-link" %>
     </li>
       <li class="nav-item">
        <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %>
      </li> -->
   </ul>
</div>


<!-- mobile nav -->

<div class="slider-menu-mobile" id="slider-menu-mobile">
  <i style="margin-left:89%;color:black !important; font-size: 34px;"  class="fas fa-ellipsis-h"></i>
</div>
   <div class="slider-menu-open-mobile" id="slider-menu-open-mobile">
      <a id="X-mobile" href="">X</a>
      <li class="nav-item active">
        <%= link_to 'Home', root_path, class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "About", "/about", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Contact", "/messages", class: "nav-link" %>
      </li>
      <li class="nav-item" id="completed-job-nav">
        <%= link_to "All completed jobs", services_path, class: "nav-link" %>
      </li>
      <%= link_to services_path(search: @search, category: 'carpet cleaning') do %>
        <p> Carpet Cleaning</p>
      <% end %>
      <%= link_to services_path(search: @search, category: 'rug cleaning') do %>
        <p> Rug Cleaning</p>
      <% end %>
      <%= link_to services_path(search: @search, category: 'curtains and blinds') do %>
        <p> Curtains and Blinds</p>
      <% end %>
      <%= link_to services_path(search: @search, category: 'karndean') do %>
        <p>Karndean</p>
      <% end %>
    </div>

app/views/static_pages/home.html.erb
    <div class="bg">
    <div class="white-split">
      <h1>
        CB Carpet Cleaning solutions.
      </h1>
      <p>*Fully checked with 10 years experience. We are the best in the game</p>
      <a class="button-green" href="mailto:someone@example.com?Subject=Hello%20again" target="_top">Email for a quote</a>
    </div>
    <div class="services">
      <div class="center-text">
      <h5 id="section1"><a href="#section2">See Services</a></h5>
      <p>this is some text about this</p>
      </div>
      <div class="center-text">
        <h5 id="reviews-link"><a href="#section3">Reviews</a></h5>
        <p>this is some text too </p>
      </div>
    </div>
    <div class="slider-menu" id="slider-menu">
      <p>More</p>
    </div>
    <div class="slider-menu-open" id="slider-menu-open">
      <a id="X" href="">X</a>
        <%= link_to services_path(search: @search, category: 'carpet cleaning') do %>
          <button type="button" class="btn btn-light" id="filter-btn"> Carpet Cleaning </button>
        <% end %>
        <%= link_to services_path(search: @search, category: 'rug cleaning') do %>
          <button type="button" class="btn btn-light" id="filter-btn"> Rug Cleaning </button>
        <% end %>
        <%= link_to services_path(search: @search, category: 'curtains and blinds') do %>
          <button type="button" class="btn btn-light" id="filter-btn"> Curtains and Blinds </button>
        <% end %>
        <%= link_to services_path(search: @search, category: 'karndean') do %>
          <button type="button" class="btn btn-light" id="filter-btn"> Karndean </button>
        <% end %>
    </div>
  </div>



<div class="section2-hp" id="section2">
  <h1 class="center-text padding">Our Services</h1>
    <h5 class="center-text">We offer a plethora of  services</h6>


  <div class="cards">
    <%= link_to services_path(search: @search, category: 'rug cleaning') do %>
    <div class="card" style="background-image:url(https://i.pinimg.com/originals/db/86/12/db861287aa298a805dab2ce4e00d5718.jpg)">
      <div class="tag">
        <p>Rug Cleaning</p>
      </div>
    </div>
   <% end %>
   <%= link_to services_path(search: @search, category: 'carpet cleaning') do %>
    <div class="card" style="background-image:url(https://www.carpetright.co.uk/media/catalog/product/cache/1/image/600x600/9df78eab33525d08d6e5fb8d27136e95/1/3/x1362-roomshot-boston-2.jpg.pagespeed.ic.zVmTJ034n0.jpg">
      <div class="tag">
        <p>Carpet Cleaning</p>
      </div>
    </div>
   <% end %>
   <%= link_to services_path(search: @search, category: 'carpet cleaning') do %>
    <div class="card" style="background-image:url(https://images.homedepot-static.com/productImages/4f695ba2-13cf-49a7-9211-3a369e2aa2e1/svn/blue-ridge-hardwood-flooring-solid-hardwood-20557-64_1000.jpg)">
      <div class="tag">
        <p>Wood Flooring</p>
      </div>
    </div>
   <% end %>
   <%= link_to services_path(search: @search, category: 'karndean') do %>
    <div class="card" style="background-image:url(https://media.woodpeckerflooring.co.uk/2016/09/30134854/product-engineered-wood-harlech-smoked-room1.jpg)">
      <div class="tag">
        <p>Karndean Maintenance</p>
      </div>
    </div>
   <% end %>
   <%= link_to services_path(search: @search, category: 'rug cleaning') do %>
    <div class="card" style="background-image:url(https://images.unsplash.com/photo-1444362408440-274ecb6fc730?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2106&q=80)">s
      <div class="tag">
        <p>Rug Cleaning</p>
      </div>
    </div>
   <% end %>
   <%= link_to services_path(search: @search, category: 'curtains and blinds') do %>
    <div class="card" style="background-image:url(https://res.cloudinary.com/dnsof9xnr/image/upload/v1558040294/14636776b5ad0016775cfd32cacd61a8.jpg)">
       <div class="tag">
        <p>Curtains & Blinds</p>
      </div>
    </div>
   <% end %>
  </div>
</div>


<div class="reviews" >
  <div class="testimonials1">
    <h2> What our customers say:</h2>
  </div>
  <div class="testimonials2">
    <h2>Testimonials:</h2>
  </div>

    <div id="carouselExampleSlidesOnly" class="carousel slide height" data-ride="carousel">
    <div class="carousel-inner height">
      <div class="carousel-item height active">
        <blockquote>
          <p>"Great Service and quick results. Will use again." </p>
          <footer>Shelly <cite title="Source Title">Leicester,UK </cite></footer>
        </blockquote>
      </div>
      <div class="carousel-item height">
         <blockquote>
          <p>"Freshened up my carpets for an affordable price" </p>
          <footer>Kate <cite title="Source Title">Leicester,UK </cite></footer>
        </blockquote>
      </div>
      <div class="carousel-item height">
         <blockquote>
          <p>"Lovley service, and great results" </p>
          <footer>Diane <cite title="Source Title" id="#section3">Leicester,UK </cite></footer>
        </blockquote>
      </div>
    </div>
  </div>
</div>


<!------ Include the above in your HEAD tag - mobile hp ---------->


 <!--  <div class="slider-menu-mobile" id="slider-menu-mobile">
    <i style="margin-left:89%;color:black !important; font-size: 34px;"  class="fas fa-ellipsis-h"></i>
   </div>
  <div class="slider-menu-open-mobile" id="slider-menu-open-mobile">
     <a id="X-mobile" href="">X</a>
     <li class="nav-item active">
       <%= link_to 'Home', root_path, class: "nav-link" %>
     </li>
     <li class="nav-item active">
       <%= link_to "About", "/about", class: "nav-link" %>
     </li>
     <li class="nav-item">
       <%= link_to "Contact", "/messages", class: "nav-link" %>
     </li>
     <li class="nav-item" id="completed-job-nav">
       <%= link_to "All completed jobs", services_path, class: "nav-link" %>
     </li>
     <%= link_to services_path(search: @search, category: 'carpet cleaning') do %>
       <p> Carpet Cleaning</p>
     <% end %>
     <%= link_to services_path(search: @search, category: 'rug cleaning') do %>
       <p> Rug Cleaning</p>
     <% end %>
     <%= link_to services_path(search: @search, category: 'curtains and blinds') do %>
       <p> Curtains and Blinds</p>
     <% end %>
     <%= link_to services_path(search: @search, category: 'karndean') do %>
       <p>Karndean</p>
     <% end %>
   </div>


  -->

  <div class="bg-mobile">
    <div class="mobile-title">
      <h1>
        CB Carpet Cleaning solutions.
      </h1>
      <p>*Fully checked with 10 years experience. We are the best in the game</p>
      <a class="button-green" href="mailto:someone@example.com?Subject=Hello%20again" target="_top">Email for a quote</a>
    </div>


</div>

  <h1 class="center-text-mobile padding services-mobile">Our Services</h1>

      <h6 class="center-text-mobile">We offer a plethora of services</h6>

    <div class="cards-mobile">
    <%= link_to services_path(search: @search, category: 'rug cleaning') do %>
      <div class="card-mobile"  style="background-image:url(https://i.pinimg.com/originals/db/86/12/db861287aa298a805dab2ce4e00d5718.jpg)">
      <div class="tag">
        <p>Rug Cleaning</p>
      </div>
    <% end %>
    </div>
    <%= link_to services_path(search: @search, category: 'carpet cleaning') do %>
    <div class="card-mobile"style="background-image:url(https://www.carpetright.co.uk/media/catalog/product/cache/1/image/600x600/9df78eab33525d08d6e5fb8d27136e95/1/3/x1362-roomshot-boston-2.jpg.pagespeed.ic.zVmTJ034n0.jpg">
      <div class="tag">
        <p>Carpet Cleaning</p>
      </div>
    </div>
    <% end %>
    <%= link_to services_path(search: @search, category: 'rug cleaning') do %>
    <div class="card-mobile"style="background-image:url(https://images.homedepot-static.com/productImages/4f695ba2-13cf-49a7-9211-3a369e2aa2e1/svn/blue-ridge-hardwood-flooring-solid-hardwood-20557-64_1000.jpg)">
        <div class="tag">
        <p>Wood Flooring</p>
      </div>
    </div>
    <% end %>
    <%= link_to services_path(search: @search, category: 'karndean') do %>
    <div class="card-mobile"style="background-image:url(https://media.woodpeckerflooring.co.uk/2016/09/30134854/product-engineered-wood-harlech-smoked-room1.jpg)">
      <div class="tag">
        <p>Karndean</p>
      </div>
    </div>
    <% end %>
    <%= link_to services_path(search: @search, category: 'rug cleaning') do %>
    <div class="card-mobile"style="background-image:url(https://images.unsplash.com/photo-1444362408440-274ecb6fc730?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2106&q=80)">
      <div class="tag">
        <p>Stains</p>
      </div>
    </div>
    <% end %>
    <%= link_to services_path(search: @search, category: 'curtain and blinds') do %>
    <div class="card-mobile"style="background-image:url(https://res.cloudinary.com/dnsof9xnr/image/upload/v1558040294/14636776b5ad0016775cfd32cacd61a8.jpg)">
      <div class="tag">
        <p>Blinds</p>
      </div>
    </div>
    <% end %>
  </div>
</div>

  <div class="reviews-mobile">
  <div class="testimonials1">
    <h2> What our customers say:</h2>
  </div>
  <div class="testimonials2">
    <h2>Testimonials:</h2>
  </div>

    <div id="carouselExampleSlidesOnly" class="carousel slide height" data-ride="carousel">
    <div class="carousel-inner height">
      <div class="carousel-item height active">
        <blockquote>
          <p>"Great Service and quick results. Will use again." </p>
          <footer>Shelly <cite title="Source Title">Leicester,UK </cite></footer>
        </blockquote>
      </div>
      <div class="carousel-item height">
         <blockquote>
          <p>"Freshened up my carpets for an affordable price" </p>
          <footer>Kate <cite title="Source Title">Leicester,UK </cite></footer>
        </blockquote>
      </div>
      <div class="carousel-item height">
         <blockquote>
          <p>"Lovley service, and great results" </p>
          <footer>Diane <cite title="Source Title">Leicester,UK </cite></footer>
        </blockquote>
      </div>
    </div>
  </div>
</div>